### ISSUE TITLE
insertFinalNewline vs. ensureSingleFinalNewline

### ISSUE THREAD

**Issue by jedmao** [jmlntw/vscode-ensure-single-final-newline#1]
The Readme says the setting is `files.insertFinalNewline`, which matches [the source code](https://github.com/jmlntw/vscode-ensure-single-final-newline/blob/3218fb19303f9522151be1dbbed78ef13bde401a/src/extension.ts#L40), but I want to point out the fact that "inserting a final newline" is totally different than "ensuring a single final newline" in that "inserting" never removes extraneous final newlines and "ensuring" add or removes, depending on the situation.

The name of this extension is great, but I suggest you change the name of the setting to match (i.e., `files.ensureSingleFinalNewline`).

What do you think?

**Comment by jedmao** [comment]
This would, of course, be a breaking change.

**Comment by jmlntw** [comment]
The reason why I use `files.insertFinalNewline` is that in most cases we don't need more than one final newlines at the end of files. Insert a newline after a existing newline is meaningless. But you're right, "insert" is different than "ensure". Maybe a independent settings value (`ensureSingleFinalNewline.enable` or something like that) should be added in the next major update.

**Comment by jedmao** [comment]
I'm most cases EditorConfig will handle the inserting of a final newline. I think the value proposition of your extension here is that it's doing something different that EditorConfig doesn't support. Are you suggesting a 2nd setting? Why add `.enable` to the end? The name `ensureSingleFinalNewline` is already named like a boolean, so `enable` would be redundant.

**Comment by jmlntw** [comment]
The settings name is just a example and may be changed.
